version: '3.4'

networks:
  net:
    name: cqrs-example-network


services:
  cqrsexample:
    image: ${DOCKER_REGISTRY-}cqrs-example
    build:
      context: .
      dockerfile: CqrsExample/Dockerfile
    networks:
      - net

  db-postgress:
    image: postgres:15-alpine 
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    networks:
      - net

  adminer:
    image: adminer
    restart: always
    networks:
      - net
