// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace ReadonlyWeatherRepository.Models;

public partial class Weather
{
    public int Id { get; set; }

    public double? Temperature { get; set; }

    public int? RegionId { get; set; }

    public virtual Region? Region { get; set; }
}